# Generated by Django 4.2.16 on 2024-12-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_dish_options_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cook",
            managers=[],
        ),
    ]
